#foo.datasource.driverClassName=com.mysql.jdbc.Driver
#foo.datasource.url=jdbc:mysql://localhost:3306/learning_spring_batch
#foo.datasource.username=root
#foo.datasource.password=p@ssw0rd
#foo.datasource.schema=schema-mysql.sql
