spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/batchdb
spring.datasource.username=batchuser
spring.datasource.password=batchuser

spring.batch.jdbc.initialize-schema=never

# Enable job execution
spring.batch.job.enabled=true
spring.batch.job.names=flowFirstJob


# Logging to see what's happening
logging.level.org.springframework.batch=DEBUG
logging.level.org.springframework.batch.core.job=INFO
logging.level.org.springframework.batch.core.step=INFO
#logging.level.org.springframework.jdbc=DEBUG

